export const disease = [
    "panic attack",
    "intellectual disability",
    "intellectual disability, Wolff type",
    "body dysmorphic disorder",
    "rejection sensitive dysphoria",
    "prepsychosis",
    "psychosis",
    "sexual dysfunction",
    "attachment disorder",
    "maladjustment",
    "impulse control disorder",
    "postpartum depression",
    "epilepsy aura",
    "codependency",
    "workaholism",
    "abandonment anxiety",
    "dissociative identity disorder",
    "Body-focused repetitive behavior disorders",
    "childhood amnesia",
    "premenstrual dysphoric disorder",
    "behavioral disorder",
    "insomnia",
    "melancholia",
    "compulsive hoarding",
    "acoasma",
    "migraine aura",
    "jet lag",
    "school refusal",
    "adjustment disorder",
    "neurodevelopmental disorder",
    "childhood fear",
    "learning disability",
    "postpartum psychosis",
    "pain disorder",
    "panic disorder",
    "eco-anxiety",
    "Dissociative stupor",
    "dissociative disorder",
    "obsessive-compulsive disorder",
    "substance use disorder",
    "emotional dysregulation",
    "social anxiety disorder",
    "encopresis",
    "integrative agnosia",
    "oppositional defiant disorder",
    "anxiety neurosis",
    "Communication deviance",
    "communication disorder",
    "Alzheimer's disease",
    "anxiety",
    "erectile dysfunction",
    "expressive aphasia",
    "phobia",
    "autism spectrum disorder",
    "personality disorder",
    "borderline personality disorder",
    "sexual addiction",
    "schizophrenia",
    "schizophrenic reaction",
    "Tourette syndrome",
    "gender identity disorder",
    "BDSM",
    "gender dysphoria",
    "gender dysphoria in children",
    "thought disorder",
    "dementia",
    "tobacco use disorder",
    "fetishism",
    "developmental disorder",
    "developmental regression",
    "developmental speech disorder",
    "post-traumatic stress disorder",
    "relationship addiction",
    "circadian rhythm sleep disorder",
    "obsession",
    "culture shock",
    "scrupulosity",
    "sexual trauma",
    "generalized anxiety disorder",
    "performance anxiety",
    "stress-related disorders",
    "executive dysfunction",
    "Late life depression",
    "binge-eating disorder",
    "trichotillomania",
    "psychological pillow",
    "Asperger syndrome",
    "complex post-traumatic stress disorder",
    "test anxiety",
    "behavioral addiction",
    "alcohol abuse",
    "sleepwalking",
    "antisocial personality disorder",
    "autism",
    "pornography addiction",
    "cognitive disorder",
    "fear",
    "Nightmare disorder",
    "Dual diagnosis",
    "sexual aversion",
    "bipolar I disorder",
    "bipolar disorder",
    "bipolar ll disorder",
    "acarophobia",
    "agoraphilia",
    "agoraphobia",
    "agraphia",
    "mood disorders",
    "Smith-Magenis syndrome",
    "Covidiot",
    "psychotic depression",
    "tic disorder",
    "Feeding disorder",
    "eating disorder",
    "compulsive act",
    "compulsive talking",
    "emotional disorder",
    "dysgraphia",
    "narcissistic personality disorder",
    "depersonalization disorder",
    "dyslexia",
    "alcoholism",
    "racial trauma",
    "Separation anxiety in dogs",
    "separation anxiety disorder",
    "Cannabis and sex",
    "cannabis abuse",
    "bipolar spectrum",
    "death anxiety",
    "reactive depression",
    "psychogenic pain",
    "language delay",
    "Internet addiction disorder",
    "Internet sex addiction",
    "memory disorder",
    "elective mutism",
    "selective mutism"
]


export const therapyType = [
    "Parent-Child Interaction (PCIT)",
    "Play Therapy",
    "Dialectical Behavior (DBT)",
    "Feminist",
    "Clinical Supervision and Licensed Supervisors",
    "Multicultural",
    "Existential",
    "EMDR",
    "Neurofeedback",
    "Intervention",
    "Solution Focused Brief (SFBT)",
    "Narrative",
    "Eclectic",
    "Internal Family Systems (IFS)",
    "Sandplay",
    "Transpersonal",
    "Integrative",
    "Acceptance and Commitment (ACT)",
    "Motivational Interviewing",
    "Gestalt",
    "Hypnotherapy",
    "Art Therapy",
    "Relational",
    "Experiential Therapy",
    "Psychodynamic",
    "Culturally Sensitive",
    "Interpersonal",
    "Person-Centered",
    "Gottman Method",
    "Jungian",
    "Mindfulness-Based (MBCT)",
    "Expressive Arts",
    "Strength-Based",
    "Trauma Focused",
    "Family / Marital",
    "Reality Therapy",
    "Humanistic",
    "Imago",
    "Adlerian",
    "Psychoanalytic",
    "Somatic",
    "Cognitive Behavioral (CBT)",
    "Coaching",
    "Neuro-Linguistic (NLP)",
    "Forensic Psychology",
    "Prolonged Exposure Therapy",
    "Family Systems",
    "Biofeedback",
    "Emotionally Focused",
    "Attachment-based",
    "Positive Psychology"
]


export const modality = [
    "Group",
    "Couples",
    "Individuals",
    "Family"
]


export const community = [
    "Immuno-disorders",
    "Sex-Positive",
    "Veterans",
    "Non-Binary Allied",
    "Queer Allied",
    "Lesbian Allied",
    "Vegan Allied",
    "HIV / AIDS Allied",
    "Bisexual Allied",
    "Transgender Allied",
    "Racial Justice Allied",
    "Kink Allied",
    "Single Mother",
    "Sex Worker Allied",
    "Little Person Allied",
    "Intersex Allied",
    "Body Positivity",
    "Blind Allied",
    "Deaf Allied",
    "Gay Allied",
    "Aviation Professionals",
    "Open Relationships Non-Monogamy",
    "Cancer"
]


export const ageBracket = [
    "Toddler",
    "Preteen",
    "Adults",
    "Teen",
    "Children (6 to 10)",
    "Elders (65+)"
]