export const mock_therapist = [
    {
      "about": "I am a culturally affirming Mental Health Therapist with over 10 yrs of experience in the field. I work with adults and young adults from diverse backgrounds, with a focus on underrepresented groups. We will identify your objectives, potential roadblocks, and strategies for overcoming them. I practice through a lens of self-compassion. My areas of expertise include, but are not limited to: Moms; life/career transitions; addiction; relationships; self-esteem; mood disorders; body image; and trauma. Therapy is a collaborative journey, and I'd like to work with you to improve the quality of your life and achieve mental well-being. As a movement therapist I understand the power of movement as it relates to moving trauma through the body. I'd love to lead you through somatic breathing and movement exercises with your permission as we work to break down barriers in your life. Therapy with me is person-centered, somatic, holistic, and empathetic. In my space you will feel seen, and heard. My overarching clinical approach is to help clients discover meaning and purpose in their lives. If you're feeling stuck, looking for meaning and purpose in your life welcome! Through this safe, collaborative journey, we will set, achieve and conquer your goals. Therapy is hard work, but we will do it together. Congrats on taking the first steps.",
      "address": "8775 Aero Drive, San Diego, 92123",
      "age": "Elders (65+), Adults, Teen",
      "community": "Aviation Professionals, Bisexual Allied, Blind Allied, Body Positivity, Cancer, Deaf Allied, Gay Allied, HIV / AIDS Allied, Immuno-disorders, Intersex Allied, Lesbian Allied, Little Person Allied, Non-Binary Allied, Queer Allied, Racial Justice Allied, Sex-Positive, Kink Allied, Single Mother, Transgender Allied, Vegan Allied, Veterans",
      "geo": "32.80964671731354,-117.13885258418729",
      "mobile": "(619) 332-2292",
      "modality": "Individuals, Couples, Group",
      "name": "Judith (Jae) Davis",
      "specialities": "stress, anxiety, depression, self esteem, school issues, career counseling, alcohol use, substance use, marital and premarital, infertility, sleep or insomnia, relationship issues, antisocial personality, coping skills, parenting, suicidal ideation, trauma and ptsd, life transitions, pregnancy, addiction, racial identity, spirituality, sex therapy, internet addiction, women's issues, transgender, behavioral issues, divorce, peer relationships, prenatal, codependency, family conflict, alzheimer's, bipoc, infidelity, life coaching, postpartum",
      "therapyType": "Acceptance and Commitment (ACT), Art Therapy, Attachment-based, Cognitive Behavioral (CBT), Culturally Sensitive, Dialectical Behavior (DBT), Existential, Expressive Arts, Feminist, Humanistic, Internal Family Systems (IFS), Interpersonal, Motivational Interviewing, Multicultural, Person-Centered, Play Therapy, Positive Psychology, Solution Focused Brief (SFBT), Somatic, Strength-Based, Trauma Focused",
      "title": "Pre-Licensed Professional, MA, APCC",
      "website": null
    },
    {
      "about": "Welcome and congratulations  for seeking help! I love working with people who want to rise up to their highest potential yet know they have some blocks to clear out of the way. Often patterns show up in our lives and we can't figure out how to change so that we are manifesting what we want in life. Don't wait any longer, get the support you deserve! I have 30 years of experience working with eating disorders, depression, compulsive behaviors & self esteem issues. I'm trained in Energy Medicine,  Energy Psychology, EMDR,& family therapy, I am also trained in Neuro Nutrient (amino acid) Therapy for depression, sleep issues, compulsions, anxiety, eating disorders or food cravings. The unique variety of my training helps me to be good at solution focused therapy that is comprehensive. I have many tools in my \"toolbox\" to teach you to use at home that will help you be your highest self.",
      "address": "Carmel, 93923",
      "age": "Elders (65+), Adults, Teen",
      "community": null,
      "geo": "52.2247482,-105.3547922",
      "mobile": "(831) 809-0999",
      "modality": "Individuals, Couples, Group",
      "name": "Mary Sue Abernethy",
      "specialities": "stress, anxiety, chronic illness, depression, self esteem, sexual abuse, emotional disturbance, sleep or insomnia, relationship issues, eating disorders, coping skills, domestic abuse, weight loss, anger management, suicidal ideation, trauma and ptsd, eft, self-harming, chronic pain, addiction, bipolar disorder, obsessive-compulsive (ocd), energy medicine, grief, obesity, divorce, codependency, family conflict, impulse control disorders, impulse control disorders",
      "therapyType": "Cognitive Behavioral (CBT), EMDR, Eclectic, Mindfulness-Based (MBCT), Person-Centered, Solution Focused Brief (SFBT)",
      "title": "Marriage & Family Therapist, BS, MA, RD, MFT, NNTS",
      "website": "https://out.psychologytoday.com/us/profile/68177/website-redirect"
    },
    {
      "about": "Jade Tree is a collective of psychotherapists who offer holistic, professional, artful, compassionate therapy for adults, couples and adolescents.  We tailor our caring, hands-on approach to each client, and our aim is to help you become the person you want to be. We believe that real lasting change is possible, and we have the skill and dedication to help you get there. We take a holistic approach, drawing on wisdom from your body, mind and spirit to get you where you want to be. We integrate psychodynamic therapy- which explores how your psychological, emotional and relational set points got formed- with somatic work, mindfulness, meditation, EMDR and Jungian dream analysis. We believe the real relationship that forms between the client and therapist can be one of the biggest factors in healing. Reach out to us today for a free phone consult to see if we are a good fit. We look forward to hearing from you.",
      "address": "Los Angeles, 90042",
      "age": "Adults, Teen, Preteen",
      "community": "Bisexual Allied, Gay Allied, Lesbian Allied, Non-Binary Allied, Queer Allied, Transgender Allied",
      "geo": "34.0536909,-118.242766",
      "mobile": "(323) 747-7238",
      "modality": "Individuals, Couples, Group",
      "name": "Jade Tree Holistic Psychotherapy",
      "specialities": "stress, anxiety, depression, self esteem, substance use, marital and premarital, emotional disturbance, infertility, sleep or insomnia, relationship issues, coping skills, trauma and ptsd, self-harming, life transitions, spirituality, women's issues, grief, peer relationships, codependency, family conflict, infidelity, life coaching",
      "therapyType": "Attachment-based, EMDR, Existential, Expressive Arts, Humanistic, Integrative, Interpersonal, Jungian, Mindfulness-Based (MBCT), Psychoanalytic, Psychodynamic, Somatic, Transpersonal",
      "title": "Marriage & Family Therapist",
      "website": "https://out.psychologytoday.com/us/profile/87608/website-redirect"
    },
    {
      "about": "There is no such thing as an ideal client other than one that takes the first steps to help better themselves. I am here to aid the process. Everyone has a purpose. Mine is to help people using different modalities catered to individual needs. I hope that every person that I assist learns self confidence, gains emotional intelligence, learns to self reflect, and builds healthy strategies to face the difficulties life can bring. We cannot always control the things in our paths but we can learn to control ourselves and how we cope with hardships. We have the ability to turn unfortunate events into beautiful testimony. I am passionate about the work that I do and I feel blessed to be part of your journey. I specialize in emotional disturbances, ADHD, socialization, self-esteem, loss, group homes, abuse, adjusting from being in the system, as well as couples and families.  I also work with adults with work stress, depression, anxiety, and divorce. Are you ready to take a leap into your wellness journey? We can work together to explore your wants and needs while gaining clarity for the mind, body, and soul. As a team we can exceed  your limitations so that you can learn to excel though your expectations and barriers. If you are ready to feel better and reach your goals lets get started!",
      "address": "Walnut Creek, 94596",
      "age": "Elders (65+), Adults, Teen, Preteen, Children (6 to 10), Toddler",
      "community": "Racial Justice Allied, Single Mother, Veterans",
      "geo": "37.9020731,-122.0618702",
      "mobile": "(909) 245-8060",
      "modality": "Individuals, Couples, Group",
      "name": "Ashlee Nikole Frazier",
      "specialities": "asperger's syndrome, stress, anxiety, adoption, depression, self esteem, school issues, teen violence, marital and premarital, sleep or insomnia, relationship issues, antisocial personality, coping skills, anger management, parenting, suicidal ideation, life transitions, child, addiction, bipolar disorder, racial identity, women's issues, behavioral issues, grief, divorce, peer relationships, autism, codependency, family conflict, adhd, impulse control disorders, impulse control disorders",
      "therapyType": "Art Therapy, Cognitive Behavioral (CBT), Family / Marital, Family Systems, Person-Centered, Solution Focused Brief (SFBT), Trauma Focused",
      "title": "Marriage & Family Therapist Associate, MA",
      "website": "https://out.psychologytoday.com/us/profile/963330/website-redirect"
    },
    {
      "about": "Choose to live your life to the fullest! I can help you on your journey. I provide positive solutions focused psychological services that help you to deal effectively with life's challenges. For many people therapy can be anxiety producing and uncomfortable. I work hard to make you feel comfortable while achieving your treatment goals. My clients often comment on how helpful and easy it is to talk with me. Experience treating anxiety, depression, relationship problems, performance issues, life and career adjustments, and phase of life struggles. Short-term and long-term treatment is available. I am very effective working with all populations. Treatment background includes working with a wide variety of diagnoses including anxiety, depression, substance abuse, chronic pain conditions, and trauma. Additionally, I have a specialty in working with athletes with on performance anxiety, goal achievement, injury rehabilitation, and career adjustment. Because I believe the relationship and connection between the client and therapist is so important, and can produce great changes, I offer a free consultation so you can feel comfortable that you are making the right choice in working with me.",
      "address": "1434 3rd Street, Napa, 94558",
      "age": "Elders (65+), Adults",
      "community": null,
      "geo": "38.29611348979592,-122.28784981632654",
      "mobile": "(707) 321-1132",
      "modality": "Individuals, Couples, Group",
      "name": "Kurt Meyers",
      "specialities": "anxiety, depression, self esteem, school issues, career counseling, substance use, sports performance, sleep or insomnia, relationship issues, coping skills, domestic abuse, men's issues, pain management, weight loss, anger management, parenting, trauma and ptsd, chronic pain, spirituality, internet addiction, gambling, transgender, obsessive-compulsive (ocd), behavioral issues, grief, obesity, video game addiction, divorce, peer relationships, family conflict, adhd, domestic violence, life coaching, impulse control disorders, impulse control disorders",
      "therapyType": "Acceptance and Commitment (ACT), Cognitive Behavioral (CBT), Mindfulness-Based (MBCT), Solution Focused Brief (SFBT)",
      "title": "Psychologist, PsyD",
      "website": "https://out.psychologytoday.com/us/profile/75050/website-redirect"
    }]